const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth"})}
function openRolePicker(){document.querySelector(".roleStrip")?.scrollIntoView({behavior:"smooth"})}
function toast(title,text){$("#toastTitle").textContent=title;$("#toastText").textContent=text;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),3200)}
const roleData={
 personal:["👤","Personal Guardian","Daily safety, route intelligence, family awareness, utilities, hospital access and emergency guidance — explained in normal language."],
 family:["👨‍👩‍👧","Family Resilience","Individual family safety, mobility needs, medication readiness, school status, safe meeting points and earlier assistance for vulnerable members."],
 business:["🏢","Business Continuity","Operational disruption, backup duration, supply-chain exposure and the process that should receive protection first."],
 hospital:["🏥","Critical Facility Continuity","Power, water, oxygen, communications, ambulance access and the countdown to service interruption."],
 authority:["🏙️","Authority Command View","System-wide cascade intelligence, population exposure, Break-the-Chain interventions, resource allocation and optimized recovery."]
};
$$('.role').forEach(b=>b.onclick=()=>{$$('.role').forEach(x=>x.classList.remove('active'));b.classList.add('active');const d=roleData[b.dataset.role];$('.roleIcon').textContent=d[0];$('#roleSummary h3').textContent=d[1];$('#roleSummary p').textContent=d[2];toast('Experience switched',d[1])});
const replies=[
['travel','Yes. Your Home → College route is currently safe. If rainfall increases this evening, Road C is the better return route because Road B has higher modeled water accumulation.'],
['power','Power is expected to remain stable tonight under the current scenario. The main upstream dependency is Substation 4. If its risk rises, I would tell you when to charge phones and backup batteries.'],
['family','All four registered family profiles are currently outside predicted high-risk zones. I am watching the school route and the grandparent priority profile more closely because their response needs are different.'],
['go','If flooding worsens, Community Shelter 3 is the current recommended safe location. Use Home → Road C → Shelter 3; Road B is the route to avoid.'],
['flood','Flood risk near your immediate location is currently low at 12%. Road B is the first nearby route likely to become unsafe if rainfall intensifies.'],
['hospital','Hospital A is currently reachable in about 11 minutes through Road C. Hospital B is the backup if the primary route or facility becomes unavailable.']
];
function askPreset(t){$('#askInput').value=t;askNexus()}
function askNexus(){const i=$('#askInput'),text=i.value.trim();if(!text)return;const w=$('#chatWindow');w.insertAdjacentHTML('beforeend',`<div class="msg user"><b>You</b><p>${text.replace(/[<>]/g,'')}</p></div>`);let ans='I can evaluate that using your current area, route, utilities, nearby critical services and the active scenario. For this prototype, try asking about travel, power, flooding, family, hospital access or where to go.';const lower=text.toLowerCase();for(const [k,v] of replies){if(lower.includes(k)){ans=v;break}}setTimeout(()=>{w.insertAdjacentHTML('beforeend',`<div class="msg ai"><b>NEXUS-Ω</b><p>${ans}</p></div>`);w.scrollTop=w.scrollHeight},350);i.value='';w.scrollTop=w.scrollHeight}
function triggerRouteAlert(){toast('Route Guardian','Rain increased: use Road C for the return journey and avoid Road B.');$('.hazard').style.transform='scale(1.15)'}
function checkFamily(){toast('Family Guardian','4/4 outside high-risk zones. Grandparent readiness and School B route remain priority watches.')}
function toggleEmergency(){const e=$('#emergencyPhone');e.classList.toggle('active');toast('Emergency Copilot',e.classList.contains('active')?'Emergency guidance expanded.':'Emergency preview returned to normal.')}
const orgData={
business:{cls:'businessVisual',ey:'BUSINESS CONTINUITY',title:'Protect the process that cannot stop.',text:'If Substation 4 fails, Cold Storage 2 becomes critical after approximately three hours. NEXUS-Ω recommends generator priority for that unit before non-critical office loads.',decision:'Reserve generator priority for Cold Storage 2',why:'Why: highest potential inventory loss + limited thermal tolerance.',metrics:[['OPERATIONS TODAY','Normal'],['CRITICAL BACKUP','2h 48m'],['HIGHEST DEPENDENCY','Cold Storage 2']]},
hospital:{cls:'hospitalVisual',ey:'HOSPITAL CONTINUITY',title:'Know how long every critical service can continue.',text:'Hospital A has strong electrical backup but weaker water continuity. Pump 2 is the hidden dependency that could reduce operational resilience during a prolonged upstream outage.',decision:'Prepare secondary power for Pump 2',why:'Why: water continuity becomes the limiting service before electricity backup is exhausted.',metrics:[['POWER BACKUP','9h'],['WATER CONTINUITY','3h 10m'],['OXYGEN RESERVE','14h']]},
authority:{cls:'authorityVisual',ey:'AUTHORITY COMMAND',title:'See the whole cascade — and where to stop it.',text:'Extreme rain can flood Road B, isolate Substation 4, interrupt Pump 2 and threaten Hospital A. Ω-CORE compares interventions and finds the highest-leverage action.',decision:'BREAK THE CHAIN → Protect Pump 2',why:'Projected cascade risk: 84% → 23% with targeted backup power.',metrics:[['CASCADE RISK','84%'],['PEOPLE EXPOSED','8,420'],['TIME TO FAILURE','1h 42m']]}
};
$$('.orgTab').forEach(b=>b.onclick=()=>{$$('.orgTab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const d=orgData[b.dataset.org];$('#orgVisual').className='orgVisual '+d.cls;$('#orgEyebrow').textContent=d.ey;$('#orgTitle').textContent=d.title;$('#orgText').textContent=d.text;$('#orgDecision').textContent=d.decision;$('#orgWhy').textContent=d.why;$('#orgVisual').innerHTML=d.metrics.map(m=>`<div class="orgMetric"><small>${m[0]}</small><b>${m[1]}</b></div>`).join('')});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});$$('.reveal').forEach(e=>io.observe(e));setTimeout(()=>$$('.hero .reveal').forEach(e=>e.classList.add('show')),100);
function updateClock(){const d=new Date();$('#clockText').textContent=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})+' • monitoring'}updateClock();setInterval(updateClock,60000);